module.exports = {
  alias: require('./alias'),
  app: require('./app'),
  batch: require('./batch'),
  bulk: require('./bulk'),
  error: require('./error'),
  generic: require('./generic'),
  admin: require('./admin'),
  server: require('./server'),
  user: require('./user'),
  conf: require('./conf'),
  db: require('./db'),
  level: require('./level'),
  log: require('./log'),
  security: require('./security'),
  template: require('./template'),
  doc: require('./doc'),
  view: require('./view'),
  attach: require('./attach'),
  options: require('./options'),
  rc: require('./rc'),
  replicate: require('./replicate'),
}
