write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-SECURITY" "1" "August 2014" "rlx-security 1.0" "User Commands"
.SH "NAME"
rlx-security
.SH "DESCRIPTION"
.SH "SYNOPSIS"

.LT
 rlx security <command> <args>
 rlx sec <command> <args>
.PP
Get or set security document.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Get the security document.
.IP "\[ci]" 4
\fBset\fR: Set the security document.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
