.TH "RLX-BULK" "1" "October 2014" "rlx-bulk 0.1.413" "User Commands"
.SH "NAME"
rlx-bulk -- [object Object]
.SH "USAGE"

.SP
rlx bulk <command> [\-l] [\-l|\-\-long] [\-\-strict] [\-\-lenient]
.br
    [\-\-flat|\-\-no\-flat] [\-\-auto\-id|\-\-no\-auto\-id] <args> 
.br
rlx bulk ls <args> <id...> <dir> 
.br
rlx bulk push <args> <dir> 
.br
rlx bulk pull <args> <id...> <dir> 
.br
rlx bulk revs <args> <id...> 
.br
rlx bulk rm <args> <id...>
.SH "DESCRIPTION"
.PP
Commands for operating on multiple documents.
.PP
You may \fBpush\fR an arbitrary directory of json documents as a bulk database operation but first it is recommended you inspect the output of the \fBls\fR command to verify the document collation is as desired.
.PP
Use the \fB\-g | \-\-glob\fR option to filter bulk operations.
.PP
If no subcommand is specified an error is reported.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List documents.
.IP "\[ci]" 4
\fBpush\fR: Push a directory of documents.
.IP "\[ci]" 4
\fBpull\fR: Pull documents to a directory.
.IP "\[ci]" 4
\fBrevs\fR: Fetch multiple document revisions.
.IP "\[ci]" 4
\fBrm\fR: Delete multiple documents.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-l, \-\-long\fR: Long listing (include documents).
.IP "\[ci]" 4
\fB\-\-strict\fR: Abort on error.
.IP "\[ci]" 4
\fB\-\-lenient\fR: Skip errors in a bulk response.
.IP "\[ci]" 4
\fB\-\-[no]\-flat\fR: Use flat collation (no attachments).
.IP "\[ci]" 4
\fB\-\-[no]\-auto\-id\fR: Use automatic id generation.
.EL
.SH "LAYOUT"
.SH "DOCUMENT\-LIST"
.SH "DOCUMENT\-IDENTIFIERS"
.SH "DOCUMENT\-COLLATION"
.SH "BULK\-DELETION"
.SH "BULK\-REVISIONS"
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
