.TH "RLX-BATCH" "1" "September 2014" "rlx-batch 0.1.286" "User Commands"
.SH "NAME"
rlx-batch -- Batch file execution.
.SH "SYNOPSIS"

.SP
rlx batch <command> <args> 
.br
rlx batch parse <args> <file...>
.SH "DESCRIPTION"
.PP
Parse and execute batch files.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBparse\fR: Parse files and print result.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
