.TH "RLX-SYSTEM" "1" "September 2014" "rlx-system 0.1.311" "User Commands"
.SH "NAME"
rlx-system -- System utilities.
.SH "SYNOPSIS"

.SP
rlx system <command> <args>
.br
rlx sys <command> <args> 
.br
rlx sys log <args> 
.br
rlx sys jar <args> 
.br
rlx sys prg <args> 
.br
rlx sys req <args> 
.br
rlx sys dbh <args> 
.br
rlx sys env <args> 
.br
rlx sys err <args> 
.br
rlx sys hist <args> 
.br
rlx sys conf <args> 
.br
rlx sys auth <args>
.SH "DESCRIPTION"
.PP
System debugging utilities.
.PP
The \fBlog\fR command accepts the \fB\-\-raw\fR option as an alternative to the default JSON output.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBlog\fR: Print log buffer contents.
.IP "\[ci]" 4
\fBjar\fR: Print cookie jar.
.IP "\[ci]" 4
\fBprg\fR: Print state of program.
.IP "\[ci]" 4
\fBreq\fR: Print state of middleware request object.
.IP "\[ci]" 4
\fBdbh\fR: Print state of database handle.
.IP "\[ci]" 4
\fBenv\fR: Print environemnt variables.
.IP "\[ci]" 4
\fBerr\fR: Print exceptions encountered.
.IP "\[ci]" 4
\fBhist\fR: Print command history.
.IP "\[ci]" 4
\fBconf\fR: Print program configuration.
.IP "\[ci]" 4
\fBauth\fR: Print current authentication information.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
