write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-TASKS" "1" "August 2014" "rlx-tasks 1.0" "User Commands"
.SH "NAME"
rlx-tasks
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx tasks <args>\fR
.PP
Print active tasks. 
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
