.TH "RLX-JSON" "1" "September 2014" "rlx-json 0.1.396" "User Commands"
.SH "NAME"
rlx-json
.SH "USAGE"

.SP
rlx json <command> [\-\-flat] <args>
.br
rlx j <command> [\-\-flat] <args> 
.br
rlx j grep <args> <ptn...> <file...>
.SH "DESCRIPTION"
.PP
Grep JSON and more.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBgrep, re\fR: Find objects matching a pattern.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-flat\fR: Flatten object keys, joined on a period.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
