.TH "RLX-VIEW" "1" "August 2014" "rlx-view 0.1.77" "User Commands"
.SH "NAME"
rlx-view -- Manage database views.
.SH "SYNOPSIS"

\fBrlx view <command> <args>\fR
.SH "DESCRIPTION"
.PP
Commands for managing database views.
.PP
If no subcommand is specified \fBtemp\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBtemp\fR: Create and execute a temporary view.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
