.TH "RLX-LOGIN" "1" "October 2014" "rlx-login 0.1.413" "User Commands"
.SH "NAME"
rlx-login -- [object Object]
.SH "USAGE"

.SP
rlx login <args> <username> <server>
.br
rlx in <args> <username> <server>
.SH "DESCRIPTION"
.PP
Alias for the \fBsession set\fR command.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
