.TH "RLX-ADMIN" "1" "September 2014" "rlx-admin 0.1.198" "User Commands"
.SH "NAME"
rlx-admin
.SH "SYNOPSIS"

.SP
rlx admin <command> <args> 
.br
rlx admin ls <args> 
.br
rlx admin get <args> <username> 
.br
rlx admin add <args> <username> <password> 
.br
rlx admin rm <args> <username>
.SH "DESCRIPTION"
.PP
If no subcommand is specified \fBls\fR is invoked.
.PP
To add an administrator specify a username and password after the \fBadd\fR command:

  rlx admin add <username> <password>
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List administrators.
.IP "\[ci]" 4
\fBget\fR: Get an administrator.
.IP "\[ci]" 4
\fBadd\fR: Create an administrator.
.IP "\[ci]" 4
\fBrm\fR: Delete an administrator.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
