.TH "RLX-LOCAL" "1" "September 2014" "rlx-local 0.1.383" "User Commands"
.SH "NAME"
rlx-local -- Manage local documents.
.SH "USAGE"

.SP
rlx local <command> <args>
.br
rlx lcl <command> <args> 
.br
rlx lcl add <args> 
.br
rlx lcl get <args> 
.br
rlx lcl cp <args> 
.br
rlx lcl rm <args>
.SH "DESCRIPTION"
.PP
Commands for creating, deleting, retrieving and modifying \fBlocal\fR documents, it is not possible to list local documents, see the \fBcouchdb\fR documentation.
.PP
If no subcommand is specified an error is reported.
.PP
When using the \fBcp\fR command to copy a document if \fB\-\-destination\fR does not specify an absolute URL then the document is copied as a local document, ie, if you wish to copy a local document to a regular document you will need to use an absolute URL for the destination.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBadd\fR: Create a local document.
.IP "\[ci]" 4
\fBget\fR: Get a local document.
.IP "\[ci]" 4
\fBcp\fR: Copy a local document.
.IP "\[ci]" 4
\fBrm\fR: Remove a local document.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
