write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-LOGOUT" "1" "August 2014" "rlx-logout 1.0" "User Commands"
.SH "NAME"
rlx-logout
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx logout <args>\fR
.PP
Logout of current session.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
