.TH "RLX-INTERACTIVE" "1" "September 2014" "rlx-interactive 0.1.273" "User Commands"
.SH "NAME"
rlx-interactive -- Interactive REPL console.
.SH "SYNOPSIS"

.SP
rlx interactive <command> <args>
.br
rlx i <command> <args> 
.br
rlx i pwd <args> 
.br
rlx i use <args> <db> 
.br
rlx i ? <args> 
.br
rlx i dbg <args> 
.br
rlx i quit <args>
.SH "DESCRIPTION"
.PP
Launch an interactive console with \fBrlx i\fR, interactive consoles may not be nested. Help is available via \fB?\fR, \fB\-\-help\fR and \fBhelp\fR. If \fB\-\-no\-interactive\fR is specified it is ignored.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBpwd\fR: Print current location.
.IP "\[ci]" 4
\fBuse\fR: Idiomatic version of \fB\-d {db}\fR.
.IP "\[ci]" 4
\fB?\fR: Short help.
.IP "\[ci]" 4
\fBdbg\fR: Debug utilities.
.IP "\[ci]" 4
\fBexit, quit, q\fR: Quit interactive console.
.EL
.SH "ARGUMENTS"
.PP
Commands are not required in interactive mode, you may set any argument:

.SP
  \-\-http      # enable http logging
.br
  \-\-no\-http   # disable http logging
.br
  \-d {db}     # set current database
.br
  \-d          # clear current database
.br
  \-\-trace     # set log level to trace
.br
  \-\-no\-color  # disable colors
.SH "HISTORY INTERPRETER"
.PP
An experimental history command interpreter is enabled by default that recognizes index based references such as \fB!!\fR (or \fB!\-1\fR) and \fB!1\fR, 
.SH "FILES"
.PP
The history file is read and written from \fB~/.rlx/.history\fR, when this command is invoked the file (and parent directories) are created if they do not exist.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
