.TH "RLX-ALIAS" "1" "October 2014" "rlx-alias 0.1.413" "User Commands"
.SH "NAME"
rlx-alias -- [object Object]
.SH "USAGE"

.SP
rlx alias <command> <args>
.br
rlx as <command> <args> 
.br
rlx as init <args> 
.br
rlx as parse <args> <alias> 
.br
rlx as get <args> <alias> 
.br
rlx as add <args> <alias> 
.br
rlx as edit <args> 
.br
rlx as rm <args> <alias> 
.br
rlx as ls <args> 
.br
rlx as print <args>
.SH "DESCRIPTION"
.PP
Aliases allow users to map names to commonly used locations, a location being a combination of \fBserver\fR, \fBdatabase\fR, document \fBid\fR and \fBrev\fR.
.PP
Reference an alias with a colon ':' prefix.
.PP
For alias subcommands that accept an \fB<alias>\fR argument it may be specified with or without the prefix.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinit\fR: Create an alias file.
.IP "\[ci]" 4
\fBparse\fR: Parse an alias and print the result.
.IP "\[ci]" 4
\fBget\fR: Print an alias.
.IP "\[ci]" 4
\fBadd\fR: Add an alias.
.IP "\[ci]" 4
\fBedit\fR: Open the alias file in an editor.
.IP "\[ci]" 4
\fBrm\fR: Remove an alias.
.IP "\[ci]" 4
\fBls\fR: List aliases.
.IP "\[ci]" 4
\fBprint, p\fR: Print the alias file.
.EL
.SH "USAGE"
.SH "INIT"
.SH "CREATE"
.SH "EXPANSION"
.SH "INSPECT"
.SH "MATCH\-PATTERN"
.SH "FILES"
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
