.TH "RLX-ATTACH" "1" "October 2014" "rlx-attach 0.1.408" "User Commands"
.SH "NAME"
rlx-attach -- [object Object]
.SH "USAGE"

.SP
rlx attach <command> <args>
.br
rlx att <command> <args> 
.br
rlx att ls <args> 
.br
rlx att up <args> <file...> 
.br
rlx att dl <args> <patterns...> <dir> 
.br
rlx att get <args> 
.br
rlx att head <args> 
.br
rlx att rm <args>
.SH "DESCRIPTION"
.PP
Commands for creating, deleting, retrieving and modifying document attachments.
.PP
If no subcommand is specified \fBls\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List attachments.
.IP "\[ci]" 4
\fBup\fR: Upload an attachment.
.IP "\[ci]" 4
\fBdl\fR: Download an attachment.
.IP "\[ci]" 4
\fBget\fR: Get attachment information.
.IP "\[ci]" 4
\fBhead\fR: Head attachment information.
.IP "\[ci]" 4
\fBrm\fR: Remove an attachment.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
