.TH "RLX-INTERACTIVE" "1" "October 2014" "rlx-interactive 0.1.408" "User Commands"
.SH "NAME"
rlx-interactive -- [object Object]
.SH "USAGE"

.SP
rlx interactive <command> [\-\-fu|\-\-futon] [\-\-fa|\-\-fauxton]
.br
    [\-\-do|\-\-docs] <args>
.br
rlx i <command> [\-\-fu|\-\-futon] [\-\-fa|\-\-fauxton] [\-\-do|\-\-docs] <args> 
.br
rlx i who <args> 
.br
rlx i su <args> <username> <server> 
.br
rlx i pwd <args> 
.br
rlx i cd <args> <path> 
.br
rlx i open <args> <url> 
.br
rlx i ? <args> 
.br
rlx i exit <args>
.SH "DESCRIPTION"
.PP
Launch an interactive console with \fBrlx i\fR, interactive consoles may not be nested. Help is available via \fB?\fR, \fB${opt_help_long}\fR and \fB${cmd_help_long}\fR. If \fB\-\-no\-interactive\fR is specified it is ignored.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBwho\fR: List login sessions.
.IP "\[ci]" 4
\fBsu\fR: Switch user session.
.IP "\[ci]" 4
\fBpwd\fR: Print current location.
.IP "\[ci]" 4
\fBcd\fR: Set current location.
.IP "\[ci]" 4
\fBopen, o\fR: Open a URL.
.IP "\[ci]" 4
\fB?\fR: Short help.
.IP "\[ci]" 4
\fBquit, exit, q\fR: Quit interactive console.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-fu, \-\-futon\fR: Open the futon web interface.
.IP "\[ci]" 4
\fB\-\-fa, \-\-fauxton\fR: Open the fauxton web interface.
.IP "\[ci]" 4
\fB\-\-do, \-\-docs\fR: Open the couchdb documentation.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
