.TH "RLX-UUIDS" "1" "September 2014" "rlx-uuids 0.1.162" "User Commands"
.SH "NAME"
rlx-uuids
.SH "SYNOPSIS"

  rlx uuids [\-\-count=<num>] <args>
.SH "DESCRIPTION"
.PP
Print list of uuids.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-count=[num]\fR: Number of uuids to fetch. 
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
