.TH "RLX-SECURITY" "1" "September 2014" "rlx-security 0.1.399" "User Commands"
.SH "NAME"
rlx-security -- Get or set database security.
.SH "USAGE"

.SP
rlx security <command> <args>
.br
rlx sec <command> <args> 
.br
rlx sec get <args> 
.br
rlx sec set <args> 
.br
rlx sec edit <args> 
.br
rlx sec rm <args>
.SH "DESCRIPTION"
.PP
The \fBsecurity\fR commands modify the security document for a database. The \fBrm\fR subcommand is a slight misnomer as the document is not actually removed, it is shorthand for setting the security document to the empty object (\fB{}\fR) which removes all database level security.
.PP
The \fBrm\fR subcommand name was chosen for consistency with other subcommands and is more concise than \fBreset\fR.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Get the security document.
.IP "\[ci]" 4
\fBset\fR: Set the security document.
.IP "\[ci]" 4
\fBedit\fR: Edit the security document.
.IP "\[ci]" 4
\fBrm\fR: Reset the security document.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
