.TH "RLX-RUNCONF" "1" "September 2014" "rlx-runconf 0.1.190" "User Commands"
.SH "NAME"
rlx-runconf -- Runtime configuration.
.SH "SYNOPSIS"

.SP
rlx runconf <command> [\-l] [\-l|\-\-long] [\-\-search\-path=<dir...>] <args>
.br
rlx rc <command> [\-l] [\-l|\-\-long] [\-\-search\-path=<dir...>] <args>
.SH "DESCRIPTION"
.PP
Runtime configuration is provided by JSON files named \fB.rlxrc\fR.
.PP
The \fBinit\fR command when invoked with no arguments will copy the system rc file to the user directory \fB~/.rlx\fR otherwise if an output directory is specified it is copied to the target directory.
.PP
If no subcommand is specified \fBprint\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinit\fR: Copy system rc file.
.IP "\[ci]" 4
\fBls\fR: List rc files.
.IP "\[ci]" 4
\fBprint, p\fR: Print configuration.
.IP "\[ci]" 4
\fBget\fR: Get configuration property.
.IP "\[ci]" 4
\fBset\fR: Set configuration property.
.IP "\[ci]" 4
\fBrm\fR: Remove configuration property.
.IP "\[ci]" 4
\fBdir\fR: Print rc file search path.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-l, \-\-long\fR: Long listing, include file contents.
.IP "\[ci]" 4
\fB\-\-search\-path=[dir...]\fR: Append directories to the rc search path.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
