.TH "RLX-ATTACH" "1" "September 2014" "rlx-attach 0.1.150" "User Commands"
.SH "NAME"
rlx-attach -- Manage document attachments.
.SH "SYNOPSIS"

.SP
rlx attach <command> <args>
.br
rlx att <command> <args>
.SH "DESCRIPTION"
.PP
Commands for creating, deleting, retrieving and modifying document attachments.
.PP
If no subcommand is specified \fBls\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List attachments.
.IP "\[ci]" 4
\fBup\fR: Upload an attachment.
.IP "\[ci]" 4
\fBdl\fR: Download an attachment.
.IP "\[ci]" 4
\fBget\fR: Get attachment information.
.IP "\[ci]" 4
\fBhead\fR: Head attachment information.
.IP "\[ci]" 4
\fBrm\fR: Remove an attachment.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
