' rlx info <args>\n rlx meta <args>'
.TH "RLX-META" "1" "August 2014" "rlx-meta 0.1.36" "User Commands"
.SH "NAME"
rlx-meta
.SH "SYNOPSIS"

.LT
 rlx info <args>
 rlx meta <args>
.SH "DESCRIPTION"
.PP
Print server information.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
