.TH "RLX-DATABASE" "1" "August 2014" "rlx-database 0.1.23" "User Commands"
.SH "NAME"
rlx-database -- Manage databases.
.SH "DESCRIPTION"
.PP
Commands for creating, deleting and modifying databases.
.SH "SYNOPSIS"

.LT
 rlx database <command> <args>
 rlx db <command> <args>
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinfo\fR: Get database information.
.IP "\[ci]" 4
\fBexists\fR: Check database existence.
.IP "\[ci]" 4
\fBadd\fR: Create a database.
.IP "\[ci]" 4
\fBrm\fR: Remove a database.
.IP "\[ci]" 4
\fBchanges\fR: Get database changes.
.IP "\[ci]" 4
\fBcommit\fR: Ensure full commit.
.IP "\[ci]" 4
\fBcompact\fR: Compact database.
.IP "\[ci]" 4
\fBcleanup\fR: Remove stale view indices.
.IP "\[ci]" 4
\fBlimit\fR: Get or set revisions limit.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
