.TH "RLX-DOCS" "1" "September 2014" "rlx-docs 0.1.184" "User Commands"
.SH "NAME"
rlx-docs -- Bulk document tasks.
.SH "SYNOPSIS"

  rlx docs <command> <args>
.SH "DESCRIPTION"
.PP
Commands for pushing and pulling bulk documents.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBpush\fR: Push a directory of JSON documents.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
