.TH "RLX-INTERACTIVE" "1" "September 2014" "rlx-interactive 0.1.378" "User Commands"
.SH "NAME"
rlx-interactive -- Interactive REPL console.
.SH "USAGE"

.SP
rlx interactive <command> <args>
.br
rlx i <command> <args> 
.br
rlx i who <args> 
.br
rlx i su <args> <username> <server> 
.br
rlx i pwd <args> 
.br
rlx i cd <args> <path> 
.br
rlx i ? <args> 
.br
rlx i quit <args>
.SH "DESCRIPTION"
.PP
Launch an interactive console with \fBrlx i\fR, interactive consoles may not be nested. Help is available via \fB?\fR, \fB\-\-help\fR and \fBhelp\fR. If \fB\-\-no\-interactive\fR is specified it is ignored.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBwho\fR: List login sessions.
.IP "\[ci]" 4
\fBsu\fR: Switch user session.
.IP "\[ci]" 4
\fBpwd\fR: Print current location.
.IP "\[ci]" 4
\fBcd\fR: Set current location.
.IP "\[ci]" 4
\fB?\fR: Short help.
.IP "\[ci]" 4
\fBexit, quit, q\fR: Quit interactive console.
.EL
.SH "LOCATION"
.PP
Run the \fBcd\fR command to change the current location, inspect the location with \fBpwd\fR, clear the current location with \fBcd /\fR.
.PP
The \fBcd\fR command accepts '..' paths so you may drop down the location or switch parent location.
.PP
Alias shortcuts are expanded when specified as a path to \fBcd\fR.
.PP
If no explicit path or alias is specified (or the path is a \fB./\fR reference) then the path is treated as relative to the current location.
.PP
When referencing databases with forward slash characters you must URL encode the forward slash (%2F).

.SP
  cd /                      # url => /
.br
  cd http://localhost:5984  # url => http://localhost:5984
.br
  cd db                     # url => http://localhost:5984/db
.br
  cd doc                    # url => http://localhost:5984/db/doc
.br
  cd 0\-1                    # url => http://localhost:5984/db/doc?rev=0\-1
.br
  cd ../../../altdb         # url => http://localhost:5984/altdb
.br
  cd ../db                  # url => http://localhost:5984/db
.br
  cd ..                     # url => http://localhost:5984
.br
  cd ..                     # url => /
.br
  cd :lhs                   # url => https://localhost:5984
.PP
If the path starts with a known protocol (http or https) then you can expand a URL to a location:

  cd http://usr@localhost:5984/db/doc?rev=0\-1
.PP
Yields the location:

.SP
  {
.br
    "server": "http://localhost:5984",
.br
    "database": "db",
.br
    "username": "usr",
.br
    "id": "doc",
.br
    "rev": "0\-1",
.br
    "url": "http://usr@localhost:5984/db/doc?rev=0\-1"
.br
  }
.SH "ARGUMENTS"
.PP
Commands are not required in interactive mode. Provided a command is not specified in the interactive console you may also set certain arguments directly:

.SP
  \-\-http                    # enable http logging
.br
  \-\-no\-http                 # disable http logging
.br
  \-d {db}                   # set current database
.br
  \-d                        # clear current database
.br
  \-\-no\-color                # disable colors
.PP
Alternatively without the leading hyphens using the long name:

.SP
  no\-color                  # disable colors
.br
  color                     # enable colors
.br
  http log\-level debug      # enable http logging (debug)
.PP
This arguments are tested against a whitelist of property names defined in \fBconsole.cascade.allow\fR. It makes sense for some options to cascade to commands executed in the future (\fB\-\-color\fR, \fB\-\-log\-level\fR etc) however for some options it is counter\-intuitive, \fB\-\-raw\fR for example.
.PP
The default list should cater for must use cases but you may modify it if you like.
.PP
The only current known collision is between the \fBhelp\fR command and \fB\-\-help\fR option, in this case \fBhelp\fR is preferred, you can still use \fB\-\-help\fR but no shortcut is available.
.SH "HISTORY INTERPRETER"
.PP
An experimental history command interpreter is enabled by default that recognizes index based references such as \fB!!\fR (or \fB!\-1\fR) and \fB!1\fR, 
.SH "FILES"
.PP
The history file is read and written from \fB~/.rlx/.history\fR, when this command is invoked the file (and parent directories) are created if they do not exist.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
