.TH "RLX-LOG" "1" "September 2014" "rlx-log 0.1.139" "User Commands"
.SH "NAME"
rlx-log -- Tail server log file.
.SH "SYNOPSIS"

\fBrlx log [\-\-raw] [\-\-offset=<num>] [\-\-bytes=<num>] <args>\fR
.SH "DESCRIPTION"
.PP
This command attempts to parse the raw response text into an array of JSON log records. If you wish to print the raw log text specify the \fB\-\-raw\fR option.
.PP
The server will often respond with partial log records (incomplete lines) depending upon the state of the log file and the \fB\-\-offset\fR and the \fB\-\-bytes\fR options. When parsing to JSON these incomplete log records are ignored, to view these partial log records use the \fB\-\-raw\fR option.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-offset=[num]\fR: Offset in bytes for the log tail. 
.IP "\[ci]" 4
\fB\-\-bytes=[num]\fR: Bytes to be returned, default is 1000.
.IP "\[ci]" 4
\fB\-\-raw\fR: Print log records as plain text.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
