.TH "RLX-USER" "1" "August 2014" "rlx-user 0.1.79" "User Commands"
.SH "NAME"
rlx-user -- Manage server users.
.SH "SYNOPSIS"

.SP
rlx user <command> <args>
.br
rlx usr <command> <args>
.SH "DESCRIPTION"
.PP
If no subcommand is specified \fBls\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List users.
.IP "\[ci]" 4
\fBadd\fR: Create a user.
.IP "\[ci]" 4
\fBget\fR: Get a user document.
.IP "\[ci]" 4
\fBedit\fR: Edit a user document.
.IP "\[ci]" 4
\fBrm\fR: Remove a user document.
.IP "\[ci]" 4
\fBpasswd\fR: Set an existing user password.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
