.TH "RLX-SESSION" "1" "September 2014" "rlx-session 0.1.310" "User Commands"
.SH "NAME"
rlx-session -- Session authentication.
.SH "SYNOPSIS"

.SP
rlx session <command> <args>
.br
rlx sess <command> <args> 
.br
rlx sess get <args> 
.br
rlx sess set <args> 
.br
rlx sess rm <args>
.SH "DESCRIPTION"
.PP
If no subcommand is specified \fBget\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Get session authentication.
.IP "\[ci]" 4
\fBset\fR: Authenticate a session.
.IP "\[ci]" 4
\fBrm\fR: Logout a session.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
