.TH "RLX-SYSTEM" "1" "September 2014" "rlx-system 0.1.276" "User Commands"
.SH "NAME"
rlx-system -- System utilities.
.SH "SYNOPSIS"

.SP
rlx system <command> <args>
.br
rlx sys <command> <args> 
.br
rlx sys jar <args> 
.br
rlx sys auth <args> 
.br
rlx sys prg <args> 
.br
rlx sys req <args> 
.br
rlx sys dbh <args>
.SH "DESCRIPTION"
.PP
System debugging utilities.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBjar\fR: Print cookie jar.
.IP "\[ci]" 4
\fBauth\fR: Print current authentication information.
.IP "\[ci]" 4
\fBprg\fR: Print state of program.
.IP "\[ci]" 4
\fBreq\fR: Print state of middleware request object.
.IP "\[ci]" 4
\fBdbh\fR: Print state of database handle.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
