.TH "RLX-ADMIN" "1" "August 2014" "rlx-admin 1.0" "User Commands"
.SH "NAME"
rlx-admin
.SH "DESCRIPTION"
.PP
Manage server administrators.
.SH "SYNOPSIS"

\fB rlx admin <command> <args>\fR
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List administrators.
.IP "\[ci]" 4
\fBget\fR: Get an administrator.
.IP "\[ci]" 4
\fBadd\fR: Create an administrator.
.IP "\[ci]" 4
\fBrm\fR: Delete an administrator.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx\-node/issues.
