.TH "RLX-TEMPLATE" "1" "August 2014" "rlx-template 0.1.44" "User Commands"
.SH "NAME"
rlx-template
.SH "SYNOPSIS"

.SP
rlx template <command> <args>
.br
rlx tpl <command> <args>
.SH "DESCRIPTION"
.PP
Manage template files.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List templates.
.IP "\[ci]" 4
\fBget\fR: Print template file.
.IP "\[ci]" 4
\fBparse\fR: Parse template file and print result.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
