.TH "RLX-JSON" "1" "October 2014" "rlx-json 0.1.408" "User Commands"
.SH "NAME"
rlx-json -- [object Object]
.SH "USAGE"

.SP
rlx json <command> [\-\-flat] [\-\-keys|\-\-no\-keys] [\-\-values] <args>
.br
rlx j <command> [\-\-flat] [\-\-keys|\-\-no\-keys] [\-\-values] <args> 
.br
rlx j grep <args> <ptn...> <file...>
.SH "DESCRIPTION"
.PP
JSON documents are parsed synchronously using the parse method provided by V8, the behaviour with very large documents is unknown.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBgrep, re\fR: Find objects matching a pattern.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-flat\fR: Flatten object keys, joined on a period.
.IP "\[ci]" 4
\fB\-\-[no]\-keys\fR: Include keys in the search.
.IP "\[ci]" 4
\fB\-\-values\fR: Include values in the search.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
