.TH "RLX-BATCH" "1" "October 2014" "rlx-batch 0.1.408" "User Commands"
.SH "NAME"
rlx-batch -- [object Object]
.SH "USAGE"

.SP
rlx batch <command> <args> 
.br
rlx batch parse <args> <file...> 
.br
rlx batch exec <args> <file...>
.SH "DESCRIPTION"
.PP
Parse and execute batch files.
.PP
Batch files are executed in the context of the current process.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBparse\fR: Parse files and print result.
.IP "\[ci]" 4
\fBexec\fR: Execute batch files.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
