write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-LINT" "1" "August 2014" "rlx-lint 1.0" "User Commands"
.SH "NAME"
rlx-lint
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx lint <args>\fR
.PP
Lint javascript and json.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
