write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-STATS" "1" "August 2014" "rlx-stats 1.0" "User Commands"
.SH "NAME"
rlx-stats
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx stats <args>\fR
.PP
Print server statistics.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
