.TH "RLX-DOCUMENT" "1" "August 2014" "rlx-document 0.1.49" "User Commands"
.SH "NAME"
rlx-document
.SH "SYNOPSIS"

.SP
rlx document <command> <args>
.br
rlx doc <command> <args>
.SH "DESCRIPTION"
.PP
Manage documents.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List documents.
.IP "\[ci]" 4
\fBadd\fR: Create a document.
.IP "\[ci]" 4
\fBget\fR: Get a document.
.IP "\[ci]" 4
\fBrm\fR: Remove a document.
.IP "\[ci]" 4
\fBhead, rev\fR: Get a document revision.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
