write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-LIST" "1" "August 2014" "rlx-list 1.0" "User Commands"
.SH "NAME"
rlx-list
.SH "DESCRIPTION"
.SH "SYNOPSIS"

.LT
 rlx list <args>
 rlx ls <args>
.PP
List databases.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
