write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-UUIDS" "1" "August 2014" "rlx-uuids 1.0" "User Commands"
.SH "NAME"
rlx-uuids
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx uuids [\-\-count=<num>] <args>\fR
.PP
Print list of uuids.
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-count=[num]\fR: Number of uuids to fetch. 
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
