.TH "RLX-LEVEL" "1" "September 2014" "rlx-level 0.1.182" "User Commands"
.SH "NAME"
rlx-level -- Get or set the server log level.
.SH "SYNOPSIS"

.SP
rlx level <command> <args>
.br
rlx lvl <command> <args>
.SH "DESCRIPTION"
.PP
If no subcommand is specified \fBget\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinfo\fR: Set log level to \fBinfo\fR.
.IP "\[ci]" 4
\fBdebug\fR: Set log level to \fBdebug\fR.
.IP "\[ci]" 4
\fBerror\fR: Set log level to \fBerror\fR.
.IP "\[ci]" 4
\fBwarn\fR: Set log level to \fBwarning\fR.
.IP "\[ci]" 4
\fBnone\fR: Set log level to \fBnone\fR.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
