.TH "RLX-DATABASE" "1" "August 2014" "rlx-database 0.1.118" "User Commands"
.SH "NAME"
rlx-database -- Manage databases.
.SH "SYNOPSIS"

.SP
rlx database <command> <args>
.br
rlx db <command> <args>
.SH "DESCRIPTION"
.PP
Commands for creating, deleting and modifying databases.
.PP
If no subcommand is specified \fBls\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List databases.
.IP "\[ci]" 4
\fBinfo, meta\fR: Get database information.
.IP "\[ci]" 4
\fBexists\fR: Check database existence.
.IP "\[ci]" 4
\fBadd\fR: Create a database.
.IP "\[ci]" 4
\fBbulk\fR: Bulk insert/update.
.IP "\[ci]" 4
\fBrm\fR: Remove a database.
.IP "\[ci]" 4
\fBtemp\fR: Execute a temporary view.
.IP "\[ci]" 4
\fBchanges\fR: Get database changes.
.IP "\[ci]" 4
\fBcommit\fR: Ensure full commit.
.IP "\[ci]" 4
\fBcompact\fR: Compact database.
.IP "\[ci]" 4
\fBcleanup\fR: Remove stale view indices.
.IP "\[ci]" 4
\fBupdates\fR: Poll for database updates.
.IP "\[ci]" 4
\fBlimit\fR: Get or set revisions limit.
.IP "\[ci]" 4
\fBpurge\fR: Purge documents.
.IP "\[ci]" 4
\fBmissingrevs, mrevs\fR: Get document revisions that do not exist.
.IP "\[ci]" 4
\fBrevsdiff, rdiff\fR: Get document revisions diff.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
