.TH "RLX-APPLICATION" "1" "October 2014" "rlx-application 0.1.408" "User Commands"
.SH "NAME"
rlx-application -- [object Object]
.SH "USAGE"

.SP
rlx application <command> <args>
.br
rlx app <command> <args> 
.br
rlx app ls <args> 
.br
rlx app push <args> <dir> 
.br
rlx app deploy <args> <dir> 
.br
rlx app get <args> 
.br
rlx app info <args> 
.br
rlx app cp <args> 
.br
rlx app head <args> 
.br
rlx app attach <args> 
.br
rlx app view <args> 
.br
rlx app update <args> 
.br
rlx app show <args> 
.br
rlx app list <args> 
.br
rlx app rewrite <args> [verb] <path> 
.br
rlx app rm <args>
.SH "DESCRIPTION"
.PP
Commands for managing applications (design documents).
.PP
If no subcommand is specified \fBls\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List design documents.
.IP "\[ci]" 4
\fBpush\fR: Push a design document.
.IP "\[ci]" 4
\fBdeploy\fR: Deploy views in live environment.
.IP "\[ci]" 4
\fBget\fR: Get a design document.
.IP "\[ci]" 4
\fBinfo\fR: Get design document information.
.IP "\[ci]" 4
\fBcp\fR: Copy a design document.
.IP "\[ci]" 4
\fBhead\fR: Get minimal design document information.
.IP "\[ci]" 4
\fBattach, att\fR: Attachment commands for design documents.
.IP "\[ci]" 4
\fBview\fR: Query a design document view.
.IP "\[ci]" 4
\fBupdate\fR: Put a design document update.
.IP "\[ci]" 4
\fBshow\fR: Show a document.
.IP "\[ci]" 4
\fBlist\fR: Run a list function on a view.
.IP "\[ci]" 4
\fBrewrite\fR: Run a rewrite rule path.
.IP "\[ci]" 4
\fBrm\fR: Remove a design document.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
