.TH "RLX-SESSION" "1" "August 2014" "rlx-session 0.1.58" "User Commands"
.SH "NAME"
rlx-session
.SH "SYNOPSIS"

.SP
rlx session <command> <args>
.br
rlx sess <command> <args>
.SH "DESCRIPTION"
.PP
Session authentication.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Get session authentication.
.IP "\[ci]" 4
\fBset\fR: Authenticate a session.
.IP "\[ci]" 4
\fBrm\fR: Logout a session.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
