write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-SESSION" "1" "August 2014" "rlx-session 1.0" "User Commands"
.SH "NAME"
rlx-session
.SH "DESCRIPTION"
.SH "SYNOPSIS"

.LT
 rlx session <command> <args>
 rlx sess <command> <args>
.PP
Cookie\-based session authentication.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Get session authentication.
.IP "\[ci]" 4
\fBset\fR: Authenticate a session.
.IP "\[ci]" 4
\fBrm\fR: Logout a session.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
