write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-INFO" "1" "August 2014" "rlx-info 1.0" "User Commands"
.SH "NAME"
rlx-info
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx info <args>\fR
.PP
Print server information.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
