write name
write synopsis
write description
write commands
write options
write environment
write files
write examples
write exit
write history
write author
write bugs
write copyright
write see
.TH "RLX-HELP" "1" "August 2014" "rlx-help 1.0" "User Commands"
.SH "NAME"
rlx-help
.SH "DESCRIPTION"
.SH "SYNOPSIS"

\fB rlx help <command>\fR
.PP
Show help for commands.
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
