.TH "RLX-CONFIG" "1" "August 2014" "rlx-config 0.1.83" "User Commands"
.SH "NAME"
rlx-config -- Manage server configuration.
.SH "SYNOPSIS"

.SP
rlx config <command> <args>
.br
rlx conf <command> <args>
.SH "DESCRIPTION"
.PP
If no subcommand is specified \fBget\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBget\fR: Get server configuration.
.IP "\[ci]" 4
\fBset\fR: Set server configuration.
.IP "\[ci]" 4
\fBrm\fR: Delete server configuration.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
