' rlx log [--offset=<num>] [--bytes=<num>] <args>'
.TH "RLX-LOG" "1" "August 2014" "rlx-log 0.1.29" "User Commands"
.SH "NAME"
rlx-log
.SH "SYNOPSIS"

\fB rlx log [\-\-offset=<num>] [\-\-bytes=<num>] <args>\fR
.SH "DESCRIPTION"
.PP
Tail server log file. 
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-\-offset=[num]\fR: Offset in bytes for the log tail. 
.IP "\[ci]" 4
\fB\-\-bytes=[num]\fR: Bytes to be returned, default is 1000.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
