.TH "RLX-ADMIN" "1" "August 2015" "rlx-admin 0.1.420" "User Commands"
.SH "NAME"
rlx-admin -- Manage server administrators.
.SH "USAGE"

.SP
rlx admin <command> <args> 
.br
rlx admin ls <args> 
.br
rlx admin get <args> <username> 
.br
rlx admin add <args> <username> <password> 
.br
rlx admin rm <args> <username>
.SH "DESCRIPTION"
.PP
If no subcommand is specified \fBls\fR is invoked.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBls\fR: List administrators.
.IP "\[ci]" 4
\fBget\fR: Get an administrator.
.IP "\[ci]" 4
\fBadd\fR: Create an administrator.
.IP "\[ci]" 4
\fBrm\fR: Delete an administrator.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
