.TH "RLX-LOCAL" "1" "August 2014" "rlx-local 0.1.106" "User Commands"
.SH "NAME"
rlx-local -- Manage local documents.
.SH "SYNOPSIS"

.SP
rlx local <command> <args>
.br
rlx lcl <command> <args>
.SH "DESCRIPTION"
.PP
Commands for creating, deleting, retrieving and modifying \fBlocal\fR documents, it is not possible to list local documents, see the \fBcouchdb\fR documentation.
.PP
If no subcommand is specified an error is reported.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBadd\fR: Create a local document.
.IP "\[ci]" 4
\fBget\fR: Get a local document.
.IP "\[ci]" 4
\fBcp\fR: Copy a local document.
.IP "\[ci]" 4
\fBrm\fR: Remove a local document.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
