.TH "RLX" "1" "August 2014" "rlx 1.0" "User Commands"
.SH "NAME"
rlx
.SH "DESCRIPTION"
.PP
Command line interface for couchdb.
.SH "SYNOPSIS"

.LT
 rlx <command> [\-vh] [\-\-color|\-\-no\-color] [\-\-debug] [\-v|\-\-verbose]
     [\-h|\-\-help] [\-\-version] [\-s|\-\-server=<url>] <args>
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBinfo\fR: Print server information.
.IP "\[ci]" 4
\fBdatabase, db\fR: Manage databases.
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-v, \-\-verbose\fR: Print more information.
.IP "\[ci]" 4
\fB\-s, \-\-server=[url]\fR: Database server.
.IP "\[ci]" 4
\fB\-h, \-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-\-debug\fR: Enable debugging.
.IP "\[ci]" 4
\fB\-\-version\fR: Output version information and exit.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx\-node/issues.
