.TH "RLX" "1" "October 2014" "rlx 0.1.408" "User Commands"
.SH "NAME"
rlx -- [object Object]
.SH "USAGE"

.SP
rlx <command> [\-c] [\-\-color|\-\-no\-color] [\-c|\-\-compress] [\-\-log\-http]
.br
    [\-\-interactive|\-\-no\-interactive] [\-\-recursive] [\-\-noop] [\-\-force]
.br
    [\-\-help] [\-\-version] [\-s|\-\-server=<url>] [\-d|\-\-database=<name>]
.br
    [\-i|\-\-id=<id>] [\-a|\-\-attachment=<file>] [\-r|\-\-rev=<rev>]
.br
    [\-u|\-\-username=<name>] [\-p|\-\-password=<pass>] [\-o|\-\-output=<file>]
.br
    [\-f|\-\-file=<file>] [\-j|\-\-json=<json>] [\-t|\-\-template=<name>]
.br
    [\-q|\-\-query=<params...>] [\-h|\-\-header=<key:val...>]
.br
    [\-g|\-\-glob=<pattern...>] [\-\-log\-level=<level>] [\-\-destination=<url>]
.br
    [\-\-ddoc=<name>] [\-n|\-\-name=<name>] [\-\-feed=<type>] <args>
.SH "DESCRIPTION"
.PP
Designed for parity with the couchdb HTTP API, run \fBhelp <cmd>\fR for more information on individual commands, start an interactive session with \fBrlx i\fR.
.SH "COMMANDS"
.BL
.IP "\[ci]" 4
\fBadmin\fR: Manage server administrators.
.IP "\[ci]" 4
\fBuser, usr\fR: Manage server users.
.IP "\[ci]" 4
\fBdatabase, db\fR: Manage databases.
.IP "\[ci]" 4
\fBsecurity, sec\fR: Get or set database security.
.IP "\[ci]" 4
\fBdocument, doc\fR: Manage documents.
.IP "\[ci]" 4
\fBbulk\fR: Bulk document tasks.
.IP "\[ci]" 4
\fBattach, att\fR: Manage document attachments.
.IP "\[ci]" 4
\fBreplicate, repl\fR: Replicate a database.
.IP "\[ci]" 4
\fBbatch\fR: Batch file execution.
.IP "\[ci]" 4
\fBapplication, app\fR: Manage design document applications.
.IP "\[ci]" 4
\fBlocal, lcl\fR: Manage local documents.
.IP "\[ci]" 4
\fBlogin, in\fR: Login to a server.
.IP "\[ci]" 4
\fBlogout, out\fR: Logout of current session.
.IP "\[ci]" 4
\fBsession, sess\fR: Session authentication.
.IP "\[ci]" 4
\fBconfig, conf\fR: Manage server configuration.
.IP "\[ci]" 4
\fBinfo\fR: Print server information.
.IP "\[ci]" 4
\fBstats\fR: Print server statistics.
.IP "\[ci]" 4
\fBtasks\fR: Print active tasks. 
.IP "\[ci]" 4
\fBlog\fR: Tail server log file. 
.IP "\[ci]" 4
\fBrestart\fR: Restart a server.
.IP "\[ci]" 4
\fBuuids\fR: Print list of uuids.
.IP "\[ci]" 4
\fBedit\fR: Edit a document.
.IP "\[ci]" 4
\fBtpl\fR: Manage template files.
.IP "\[ci]" 4
\fBlint\fR: Lint javascript and json.
.IP "\[ci]" 4
\fBlevel, lvl\fR: Get or set the server log level.
.IP "\[ci]" 4
\fBwhoami\fR: Get current user information.
.IP "\[ci]" 4
\fBrunconf, rc\fR: Runtime configuration.
.IP "\[ci]" 4
\fBalias, as\fR: Manage alias shortcuts.
.IP "\[ci]" 4
\fBsystem, sys\fR: System utilities.
.IP "\[ci]" 4
\fBjson, j\fR: Grep JSON and more.
.IP "\[ci]" 4
\fBhttp, tt\fR: Low\-level HTTP requests.
.IP "\[ci]" 4
\fBinteractive, i\fR: Interactive REPL console.
.IP "\[ci]" 4
\fBhelp\fR: Show help for commands.
.EL
.SH "OPTIONS"
.BL
.IP "\[ci]" 4
\fB\-h, \-\-header=[key:val...]\fR: Additional HTTP headers.
.IP "\[ci]" 4
\fB\-\-[no]\-color\fR: Enable or disable terminal colors.
.IP "\[ci]" 4
\fB\-d, \-\-database=[name]\fR: Database name.
.IP "\[ci]" 4
\fB\-i, \-\-id=[id]\fR: Document identifier.
.IP "\[ci]" 4
\fB\-a, \-\-attachment=[file]\fR: Attachment file path.
.IP "\[ci]" 4
\fB\-r, \-\-rev=[rev]\fR: Document revision.
.IP "\[ci]" 4
\fB\-u, \-\-username=[name]\fR: Authentication username.
.IP "\[ci]" 4
\fB\-p, \-\-password=[pass]\fR: Authentication password.
.IP "\[ci]" 4
\fB\-o, \-\-output=[file]\fR: Write response to output file.
.IP "\[ci]" 4
\fB\-f, \-\-file=[file]\fR: Read JSON input from file.
.IP "\[ci]" 4
\fB\-j, \-\-json=[json]\fR: JSON string literal (overrides \-\-file).
.IP "\[ci]" 4
\fB\-t, \-\-template=[name]\fR: Name of a template file.
.IP "\[ci]" 4
\fB\-c, \-\-compress\fR: Compact JSON output format (zero indent). 
.IP "\[ci]" 4
\fB\-q, \-\-query=[params...]\fR: Query string parameters.
.IP "\[ci]" 4
\fB\-s, \-\-server=[url]\fR: Database server.
.IP "\[ci]" 4
\fB\-g, \-\-glob=[pattern...]\fR: File match pattern(s).
.IP "\[ci]" 4
\fB\-\-log\-level=[level]\fR: Set the log level.
.IP "\[ci]" 4
\fB\-\-log\-http\fR: Enable HTTP logs.
.IP "\[ci]" 4
\fB\-\-[no]\-interactive\fR: Disable interactive prompts.
.IP "\[ci]" 4
\fB\-\-recursive\fR: Read directories recursively.
.IP "\[ci]" 4
\fB\-\-noop\fR: Print db network requests, do not send them.
.IP "\[ci]" 4
\fB\-\-destination=[url]\fR: Copy destination.
.IP "\[ci]" 4
\fB\-\-force\fR: Force file overwrite.
.IP "\[ci]" 4
\fB\-\-ddoc=[name]\fR: Design document id.
.IP "\[ci]" 4
\fB\-n, \-\-name=[name]\fR: Design document function name (view|update|show|list).
.IP "\[ci]" 4
\fB\-\-feed=[type]\fR: Poll feed type. 
.IP "\[ci]" 4
\fB\-\-help\fR: Display this help and exit.
.IP "\[ci]" 4
\fB\-\-version\fR: Print version and exit.
.EL
.SH "BUGS"
.PP
Report bugs to https://github.com/freeformsystems/rlx/issues.
