#!/usr/bin/env node

var EOL = require('os').EOL;
var DNL = EOL + EOL;
var fs = require('fs');
var path = require('path');
var util = require('util');
var base = path.normalize(path.join(__dirname, '..'));
var qt = require('../test/fixtures/qt');
var config = require('../test/util/config');
var pkg = require('../package.json');
var exe = pkg.name;
var output = process.argv[2] || path.join(base, 'doc', 'cheatsheet.md');
var heading = util.format('# %s(1) cheatsheet', exe);
var description = 'API methods yet to be implemented are marked '
description += 'with a strikethrough.';

var sections = {
  server: 'Server',
  db: 'Database',
  doc: 'Document',
  app: 'Design Document',
  admin: 'Administrator',
  user: 'User',
  security: 'Security',
  session: 'Session',
  repl: 'Replicate',
  lcl: 'Local Document',
  att: 'Attachment',
  conf: 'Configuration',
  level: 'Log Level',
}

// map these commands to different sections
var lookup = {
  login: 'session',
  logout: 'session',
  //repl: 'repl',
  whoami: 'session'
}

var ignore = [
  'template',
  'tpl',
  'lint',
  'edit',
  '--version',
  '--help'
];

var rules = [], st = '~~';
rules.push({src: config.paths.app, rep: qt.params.directory});
rules.push({src: config.server.default, rep: qt.params.server});
rules.push({src: config.repl.target, rep: qt.params.db});
rules.push({src: config.database.default, rep: qt.params.db});
rules.push({src: config.database.users, rep: qt.params.db});
rules.push({src: config.design.auth, rep: qt.params.ddoc});


rules.push({src: config.conf.section, rep: qt.params.section});
rules.push({src: config.conf.key, rep: qt.params.key});
rules.push({src: config.conf.value, rep: qt.params.value});

rules.push({src: config.admin.name, rep: qt.params.name});
rules.push({src: config.admin.pass, rep: qt.params.pass});

rules.push({src: /(-f|--file|-o|--output) [^ ]+/gm,
            rep: '$1 ' + qt.params.file});

rules.push({src: /(-v|--view) [^ ]+/gm,
            rep: '$1 ' + qt.params.view});

rules.push({src: /(-q|--query) ([^ ]+)/gm,
            rep: '$1 \'$2\''});

rules.push({src: /(-a|--attachment) [^ ]+/gm,
            rep: '$1 ' + qt.params.attname});

rules.push({src: config.app.copy, rep: qt.params.ddoc});
rules.push({src: config.app.ddoc, rep: qt.params.ddoc});

rules.push({src: config.copy.id, rep: qt.params.docid});
rules.push({src: config.document.id, rep: qt.params.docid});
rules.push({src: /(-t|--template) ([^ ]*)/gm, rep: '$1 ' + qt.params.template});

rules.push({src: config.user.name, rep: qt.params.name});

//for(var f in config.fixtures) {
  //rules.push({src: config.fixtures[f].path, rep: qt.params.file});
  //rules.push({src: config.fixtures[f].name, rep: qt.params.name});
//}

function replace(str) {
  var i, rule, re;
  for(i = 0;i < rules.length;i++) {
    rule = rules[i];
    re = (rule.src instanceof RegExp)
      ? rule.src : new RegExp(rule.src, 'gm');
    str = str.replace(re, rule.rep);
  }
  return str;
}

function tidy(u) {
  u = u.replace(/\.html/, '');
  u = u.replace(/_/g, '-');
  u = u.replace(/-{2,}/g, '-');
  u = u.replace(/-+$/, '');
  return u;
}

function order() {
  var out = [];
  var keys = Object.keys(sections), i, k, j, item, exists, cmds, cmd;
  var seen = {};
  for(i = 0;i < keys.length;i++) {
    k = keys[i];
    section = sections[k];
    section.cmd = k;
    out.push({title: section, cmd: k === 'server' ? '' : k});
    for(j = 0;j < qt.length;j++) {
      item = qt[j];
      //if(item.section)
      cmd = item.cmd[0];
      if(lookup[cmd] && k === lookup[cmd]) {
        section = lookup[cmd];
      }
      if(~ignore.indexOf(cmd)) continue;
      if(k === 'server' && !sections[cmd] && !lookup[cmd]) {
        out.push(item);
      }else if(lookup[cmd] || k === cmd && sections[cmd]) {
        if((seen[section + ':' + item.req] && !item.duplicate)
          && item.group === undefined) {
          exists = seen[section + ':' + item.req];
          exists.code = exists.code || [getCommand(exists)];
          exists.code.push(getCommand(item));
          item.duplicate = true;
          continue;
        }

        out.push(item);
      }
      seen[section + ':' + item.req] = item;
    }
  }
  return out;
}

function getCommand(item) {
  var cmds = item.cmd.slice(0);
  cmds.unshift(exe);
  return replace(cmds.join(' '));
}

function build(qt) {
  var str = heading + DNL + description + DNL;
  var i, item, cmds, cmd, pre, post, disabled;
  for(i = 0;i < qt.length;i++) {
    item = qt[i];
    if(typeof item.title === 'string') {
      str += '## ' + item.title + DNL;
      str += '* Manual: '
        + util.format('`%s %s %s`', exe, 'help', item.cmd) + EOL;
      str += '* Help: '
        + util.format('`%s %s %s`', exe, '--help', item.cmd) + DNL;
      continue;
    }else if(item.duplicate) {
      continue;
    }
    pre = post = '';
    disabled = item.enabled === false;
    if(disabled) {
      pre = post = st;
    }
    cmds = getCommand(item);
    str += '### ' + pre + item.req + post + DNL;
    str += item.description + (disabled ? '.' : ':') + DNL;
    if(!disabled) {
      str += '```' + EOL
        + (item.code ? item.code.join(EOL) : cmds) + EOL + '```' + DNL;
    }
    str += 'Documentation: '
      + util.format('[%s](%s)', tidy(item.doc), item.url) + DNL;
  }
  return str;
}

//build(order());
process.stdout.write(build(order()));
process.exit(0);
